### ISSUE TITLE
Docker Troubleshooting

### ISSUE THREAD

**Issue by bruce3401** [dyllanwli/Solution#1]
Some tips or little usage of docker 

1. how to shrink the docker logs
    - `truncate -s 0 /var/lib/docker/containers/*/*-json.log` 
    - Though it works, but it still looks so terrible when your produced too many

**Comment by bruce3401** [comment]
shadowsocks docker-compose:

```
---
version: "3"

services:

  aes-256-cfb_ss:
    image: mritd/shadowsocks
    ports:
      - 2333:8989
    restart: always
    command: -m "ss-server" -s "-s 0.0.0.0 -p 8989 -m aes-256-cfb -k mypassword--fast-open"
```
