### ISSUE TITLE
Monitoring my machine using web interface

### ISSUE THREAD

**Issue by bruce3401** [dyllanwli/Solution#11]
Here is the docker-compose file:

```
version: '3'

services:
  netdata:
    image: netdata/netdata
    volumes: 
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    ports:
      - 19999:19999

```
